name: JQ Example - Read File

on: workflow_dispatch

jobs:
  parse-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Read JSON File
        run: |
          echo '{"name": "GitHub Actions", "version": "1.0"}' > data.json
          cat data.json | jq '.'
