name: Access Workflow Context

on: [push, pull_request]

jobs:
  context-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print Workflow Context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Triggering Actor: ${{ github.actor }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Workflow Name: ${{ github.workflow }}"
