name: Debug Workflow

on: push

jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Enable Debug Logging
        run: echo "Debug logging is enabled"
