name: Matrix Example

on: push

jobs:
  test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Print OS name
        run: echo "Running on ${{ matrix.os }}"
